// components/StatusReportFields.jsx
// ✅ PATCH: proposalNumber is now read-only — auto-generated by backend
//   Pass `orderProposalNumber` prop to display it.
//   The field is still stored in selectedOptions.proposalNumber for legacy
//   report compatibility, but is never editable here.

import React from 'react';

const STATUS_CATEGORIES = [
  'Items to be delivered during the week of installation',
  'Items shipping to Resort',
  'Items currently in transit',
  'Deliveries to Freight Forwarder',
  'Items Delivered',
  'Pending Delivery',
  'Uncategorized',
];

const SHIPPING_CARRIERS = [
  'UPS', 'FedEx', 'USPS', 'DHL', 'ABF Freight',
  'XPO Logistics', 'R+L Carriers', 'Estes Express',
  'Old Dominion', 'Saia', 'YRC Freight', 'Other'
];

// orderProposalNumber: the Hen-XXX-000001 value from the Order document
// readOnlyFields: array of selectedOptions field names to block (e.g. ['proposalNumber'])
const StatusReportFields = ({
  product,
  index,
  onUpdate,
  disabled = false,
  orderProposalNumber = null,
  readOnlyFields = [],
}) => {
  const opts = product.selectedOptions || {};
  const upd = (field, value) => {
    if (readOnlyFields.includes(field)) return; // hard block
    onUpdate(index, `selectedOptions.${field}`, value);
  };

  const inputCls = `w-full px-3 py-2 border border-gray-300 rounded-lg text-sm
    focus:ring-2 focus:ring-[#005670]/20 focus:border-[#005670]
    disabled:bg-gray-100 disabled:cursor-not-allowed`;

  // Resolve which proposal number to display:
  // prefer the order-level auto-generated one, fall back to whatever was stored
  const displayProposalNumber =
    orderProposalNumber ||
    opts.proposalNumber ||
    null;

  return (
    <div className="space-y-4">

      {/* Order Date */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1.5">Order Date</label>
        <input
          type="date"
          value={opts.orderDate || ''}
          onChange={(e) => upd('orderDate', e.target.value)}
          disabled={disabled}
          className={inputCls}
        />
      </div>

      {/* Expected Ship / Arrival */}
      <div className="grid grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1.5">Expected Ship Date</label>
          <input type="date" value={opts.expectedShipDate || ''}
            onChange={(e) => upd('expectedShipDate', e.target.value)}
            disabled={disabled} className={inputCls} />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1.5">Expected Arrival Date</label>
          <input type="date" value={opts.expectedArrivalDate || ''}
            onChange={(e) => upd('expectedArrivalDate', e.target.value)}
            disabled={disabled} className={inputCls} />
        </div>
      </div>

      {/* Date Received / Inspected */}
      <div className="grid grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1.5">Date Received</label>
          <input type="date" value={opts.dateReceived || ''}
            onChange={(e) => upd('dateReceived', e.target.value)}
            disabled={disabled} className={inputCls} />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1.5">Date Inspected</label>
          <input type="date" value={opts.dateInspected || ''}
            onChange={(e) => upd('dateInspected', e.target.value)}
            disabled={disabled} className={inputCls} />
        </div>
      </div>

      {/* Next Step / Next Step Date */}
      <div className="grid grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1.5">Next Step</label>
          <input type="text" value={opts.nextStep || ''}
            onChange={(e) => upd('nextStep', e.target.value)}
            disabled={disabled} className={inputCls} placeholder="Enter Next Step" />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1.5">Next Step Date</label>
          <input type="date" value={opts.nextStepDate || ''}
            onChange={(e) => upd('nextStepDate', e.target.value)}
            disabled={disabled} className={inputCls} />
        </div>
      </div>

      {/* Carrier + tracking + WRN  |  Notes */}
      <div className="grid grid-cols-2 gap-4">
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1.5">Shipping Carrier</label>
            <select value={opts.shippingCarrier || ''}
              onChange={(e) => upd('shippingCarrier', e.target.value)}
              disabled={disabled} className={`${inputCls} bg-white`}>
              <option value="">Select...</option>
              {SHIPPING_CARRIERS.map(c => <option key={c} value={c}>{c}</option>)}
            </select>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1.5">Tracking Number</label>
            <input type="text" value={opts.trackingInfo || ''}
              onChange={(e) => upd('trackingInfo', e.target.value)}
              disabled={disabled} className={inputCls} placeholder="Enter Tracking Number" />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1.5">Warehouse Receiving Number</label>
            <input type="text" value={opts.warehouseReceivingNumber || ''}
              onChange={(e) => upd('warehouseReceivingNumber', e.target.value)}
              disabled={disabled} className={inputCls} placeholder="Enter Warehouse Receiving Number" />
          </div>
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1.5">Notes</label>
          <textarea value={opts.notes || ''}
            onChange={(e) => upd('notes', e.target.value)}
            disabled={disabled} className={`${inputCls} resize-y`}
            rows={9} placeholder="Enter Notes" />
        </div>
      </div>

      {/* Status Report Grouping */}
      <div className="pt-2 border-t border-gray-100">
        <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-3">
          Status Report Grouping
        </p>
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1.5">Status Category</label>
            <select value={opts.statusCategory || ''}
              onChange={(e) => upd('statusCategory', e.target.value)}
              disabled={disabled} className={`${inputCls} bg-white`}>
              <option value="">Select category...</option>
              {STATUS_CATEGORIES.map(cat => <option key={cat} value={cat}>{cat}</option>)}
            </select>
          </div>

          {/* ✅ Proposal Number — read-only display, never an input */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1.5">
              Proposal Number
              <span className="ml-2 text-[10px] font-normal text-gray-400 bg-gray-100 px-1.5 py-0.5 rounded">
                auto-generated
              </span>
            </label>
            <div className={`w-full px-3 py-2 border rounded-lg text-sm flex items-center gap-2
              ${displayProposalNumber
                ? 'bg-[#005670]/5 border-[#005670]/30 text-[#005670] font-semibold font-mono'
                : 'bg-gray-50 border-gray-200 text-gray-400 italic'
              }`}
            >
              {displayProposalNumber ? (
                <>
                  <svg className="w-3.5 h-3.5 flex-shrink-0 opacity-60" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                  {displayProposalNumber}
                </>
              ) : (
                'Generated when proposal is saved'
              )}
            </div>
          </div>
        </div>
      </div>

    </div>
  );
};

export default StatusReportFields;